language: node_js
node_js:
 - "node"
install:
 - yarn install
script:
 - yarn run lint
 - yarn build
 - yarn run travis-karma-browserstack
after_script:
 - yarn run post-coveralls
 - yarn run send-codacy
